version: 2
env:
  - CGO_ENABLED=0

builds:
  - binary: tflint-ruleset-ibm
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    hooks:
      post:
        - mkdir -p ./dist/raw
        - cp "{{ .Path }}" "./dist/raw/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  disable: true

release:
  github:
    owner: uibm
    name: tflint-ruleset-ibm
  draft: true

snapshot:
  name_template: "{{ .Tag }}-dev"