version: 2

env:
  - CGO_ENABLED=0

builds:
  - binary: tflint-ruleset-ibm
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
    hooks:
      post:
        - mkdir -p ./dist/raw
        - cp "{{ .Path }}" "./dist/raw/tflint-ruleset-ibm_{{ .Os }}_{{ .Arch }}"

archives:
  - format: zip
    name_template: "tflint-ruleset-ibm_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: uibm
    name: tflint-ruleset-ibm
  draft: false
  replace_existing_draft: true
  mode: replace

snapshot:
  name_template: "{{ .Tag }}-dev"